"""
Security and Structural Guardrails Engine for the KMRL Platform.

This module enforces input sanitization (prompt injection deterrence) and 
output compliance auditing (hallucination detection, citation integrity) 
across all Large Language Model interaction pipelines.
"""

import logging
import re
from typing import Any, Dict, List, Optional

from ..preprocessing.chunker import TextChunk

logger = logging.getLogger("document_intelligence.llm.guardrails")


class GuardrailVerdict:
    """
    Data payload encapsulate the results of an isolated guardrail evaluation check.
    """
    def __init__(self, passed: bool, reason: str = "", risk_score: float = 0.0) -> None:
        self.passed = passed
        self.reason = reason
        self.risk_score = risk_score


class LLMGuardrails:
    """
    Programmatic compliance engine validating input safety thresholds 
    and output factual boundaries for LLM generation.
    """

    def __init__(self) -> None:
        # High-confidence prompt injection heuristic tokens
        self.injection_patterns = [
            re.compile(r"ignore\s+(previous|all)\s+instructions", re.IGNORECASE),
            re.compile(r"system\s+prompt\s+override", re.IGNORECASE),
            re.compile(r"you\s+are\s+now\s+a\s+malicious", re.IGNORECASE),
            re.compile(r"reprogram\s+the\s+assistant", re.IGNORECASE),
            re.compile(r"decode\s+base64", re.IGNORECASE)
        ]
        
        # Regex to locate standard citation blocks, e.g., [Doc 3] or [Source 12] or [File 1]
        self.citation_pattern = re.compile(r"\[(?:Doc|Source|File)\s+(\d+)\]", re.IGNORECASE)
        
        logger.info("Structural LLMGuardrails engine initialized with active inspection rules.")

    def validate_input_query(self, query: str) -> GuardrailVerdict:
        """
        Input Guardrail: Scans incoming requests for adversarial text profiles 
        or high-risk injection attempts before resource dispatch.

        Args:
            query: Raw user query parameter.

        Returns:
            A GuardrailVerdict containing passing state metrics.
        """
        if not query or not query.strip():
            return GuardrailVerdict(passed=False, reason="Empty query target string.")

        # Block massive buffer overruns targeting prompt context displacement
        if len(query) > 4000:
            logger.warning(f"Query length anomaly detected. Size: {len(query)} characters.")
            return GuardrailVerdict(passed=False, reason="Query exceeds absolute safe context length boundaries.")

        # Evaluate text against known injection heuristics
        for pattern in self.injection_patterns:
            if pattern.search(query):
                logger.critical(f"Adversarial prompt injection pattern matched on incoming stream: '{query}'")
                return GuardrailVerdict(passed=False, reason="Potential system prompt override attempt detected.", risk_score=1.0)

        return GuardrailVerdict(passed=True)

    def validate_output_citations(self, generated_answer: str, attached_chunks: List[TextChunk]) -> GuardrailVerdict:
        """
        Output Guardrail: Validates that any document citation claims made by the LLM 
        mathematically align with the actual context boundaries provided.
        Prevents 'Ghost Citations' where an model hallucinates file indices.

        Args:
            generated_answer: The text response generated by the model instance.
            attached_chunks: The literal source chunks provided inside the context envelope.

        Returns:
            A GuardrailVerdict enforcing citation containment.
        """
        if not generated_answer:
            return GuardrailVerdict(passed=False, reason="Empty generated output context.")

        # Find all citation indices referenced in the text payload
        found_citations = self.citation_pattern.findall(generated_answer)
        if not found_citations:
            # If the model chose not to cite anything, check if fallback terms triggered
            # (e.g. "I am sorry, but the provided documentation does not contain...")
            return GuardrailVerdict(passed=True)

        total_provided_docs = len(attached_chunks)
        
        # Cross-reference indices
        for citation_str in found_citations:
            try:
                citation_index = int(citation_str)
                # If the index is 1-based (e.g. [Doc 1]), verify bounds
                if citation_index < 1 or citation_index > total_provided_docs:
                    logger.error(
                        f"Ghost Citation Hallucination Flagged! Model referenced index [{citation_index}] "
                        f"but only {total_provided_docs} document context elements were provided."
                    )
                    return GuardrailVerdict(
                        passed=False, 
                        reason=f"Model response contained hallucinated document source marker: [Doc {citation_index}]."
                    )
            except ValueError:
                return GuardrailVerdict(passed=False, reason="Malformed structural citation integer format.")

        return GuardrailVerdict(passed=True)