"""LLM Base Client Connection Wrapper for the KMRL Platform.

Provides a unified interface for interacting with downstream text generation engines 
(Ollama, OpenAI, vLLM, Azure), managing parameters, streaming states, and failure recovery.
"""

import logging
import os
from typing import Any, Dict, Generator, Optional
from openai import OpenAI, APIError
from pydantic import BaseModel, Field, field_validator

logger = logging.getLogger("document_intelligence.llm.llm_client")


class LLMClientConfig(BaseModel):
    """
    Validates parameter settings for the generation instance.
    """
    # Changed default from 'gpt-4o-mini' to a common open-source model key (e.g., llama3)
    model_name: str = Field(default="llama3", description="Target deployment model key identifier.")
    api_key: Optional[str] = Field(default=None, description="Bearer token key. Ollama ignores this, but it keeps the client schema happy.")
    # Changed default from None to the standard local Ollama OpenAI-compatible endpoint route
    base_url: Optional[str] = Field(default="http://localhost:11434/v1", description="Custom routing target URL matching the local Ollama server endpoint.")
    temperature: float = Field(default=0.0, ge=0.0, le=2.0, description="Sampling temperature settings determining output determinism.")
    max_tokens: int = Field(default=1024, ge=1, description="Absolute limits for allocation window context sizes.")

    @field_validator("api_key", mode="before")
    @classmethod
    def resolve_api_key(cls, value: Optional[str]) -> Optional[str]:
        """Resolves missing keys from system environment variables where applicable."""
        if not value:
            # For Ollama, the api_key can be any dummy string (it is not checked by the local server)
            return os.getenv("OLLAMA_API_KEY", "ollama-local-bypass-key")
        return value


class LLMClient:
    """
    Encapsulates core connectivity and generation pathways for upstream text models.
    """

    def __init__(self, config: Optional[LLMClientConfig] = None) -> None:
        """
        Initializes the client using explicit settings or system defaults.
        """
        self.config = config or LLMClientConfig()
        
        # Configure connection layers. Passes the local Ollama URL to overwrite default OpenAI pathways
        self.client = OpenAI(
            api_key=self.config.api_key,
            base_url=self.config.base_url
        )
        logger.info(
            f"LLM Client successfully initialized. Target Local Model: '{self.config.model_name}' | "
            f"Base Endpoint: '{self.config.base_url}'"
        )

    def generate(self, system_prompt: str, user_prompt: str, response_format: Optional[Dict[str, Any]] = None) -> str:
        """
        Executes a standard block-level completion request.

        Args:
            system_prompt: System-level framing context or guardrails.
            user_prompt: The core dynamic context string or query statement.
            response_format: Optional dictionary rule to toggle JSON Mode (e.g., {"type": "json_object"}).

        Returns:
            The raw text content generated by the model.
        """
        logger.debug(f"Dispatching atomic text generation request to model: {self.config.model_name}")
        
        try:
            kwargs = {
                "model": self.config.model_name,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "temperature": self.config.temperature,
                "max_tokens": self.config.max_tokens,
            }
            if response_format:
                kwargs["response_format"] = response_format

            response = self.client.chat.completions.create(**kwargs)
            return response.choices[0].message.content or ""

        except APIError as api_err:
            logger.error(f"Downstream LLM API exception intercepted: {str(api_err)}")
            raise RuntimeError(f"LLM service provider failed to complete the request: {str(api_err)}")
        except Exception as e:
            logger.exception("Unexpected system crash inside active client generation path.")
            raise e

    def generate_stream(self, system_prompt: str, user_prompt: str) -> Generator[str, None, None]:
        """
        Executes a streaming text request, yielding tokens instantly as they generate.

        Args:
            system_prompt: System-level baseline constraints.
            user_prompt: User question or conversational turn input text.

        Yields:
            Individual token string increments for real-time frontend printing.
        """
        logger.debug(f"Dispatching real-time token stream sequence from model: {self.config.model_name}")
        
        try:
            stream = self.client.chat.completions.create(
                model=self.config.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=self.config.temperature,
                max_tokens=self.config.max_tokens,
                stream=True
            )
            
            for chunk in stream:
                if chunk.choices and chunk.choices[0].delta.content:
                    yield chunk.choices[0].delta.content

        except APIError as api_err:
            logger.error(f"Downstream LLM API exception intercepted during active stream loop: {str(api_err)}")
            raise RuntimeError(f"LLM streaming pipeline failed midway: {str(api_err)}")