"""LLM Base Client Connection Wrapper for the KMRL Platform.

Provides a unified interface for interacting with downstream text generation engines 
(Ollama, OpenAI, vLLM, Azure), managing parameters, streaming states, and failure recovery.
"""

import logging
import os
from typing import Any, Dict, Generator, Optional
from openai import OpenAI, APIError
from pydantic import BaseModel, Field, field_validator

from config.settings import LLMProvider, get_settings

logger = logging.getLogger("document_intelligence.llm.llm_client")


def _active_provider_is_ollama() -> bool:
    return get_settings().llm.active_provider is LLMProvider.OLLAMA


def _default_model_name() -> str:
    """Model tag for whichever provider `LLM_ACTIVE_PROVIDER` selects."""
    llm = get_settings().llm
    return llm.ollama_model if _active_provider_is_ollama() else llm.openai_model


def _default_base_url() -> str:
    """Base URL for the active provider's OpenAI-compatible surface.

    Ollama serves its OpenAI-compatible API under a `/v1` prefix, while the settings
    hold its plain root URL, so the suffix is applied here rather than baked into config.
    """
    llm = get_settings().llm
    if _active_provider_is_ollama():
        return f"{llm.ollama_base_url.rstrip('/')}/v1"
    return llm.openai_base_url


def _default_api_key() -> Optional[str]:
    """Bearer token for the active provider (Ollama accepts any non-empty string)."""
    if _active_provider_is_ollama():
        return os.getenv("OLLAMA_API_KEY", "ollama-local-bypass-key")
    return get_settings().llm.openai_api_key


class LLMClientConfig(BaseModel):
    """
    Validates parameter settings for the generation instance.

    Defaults are resolved from `config.settings` (the `LLM_` env prefix) so switching
    `LLM_ACTIVE_PROVIDER` between Ollama and an OpenAI-compatible endpoint reroutes the
    client without code changes.
    """
    model_name: str = Field(default_factory=_default_model_name, description="Target deployment model key identifier.")
    api_key: Optional[str] = Field(default_factory=_default_api_key, description="Bearer token key. Ollama ignores this, but it keeps the client schema happy.")
    base_url: Optional[str] = Field(default_factory=_default_base_url, description="Routing target URL for the active provider's OpenAI-compatible API.")
    temperature: float = Field(default_factory=lambda: get_settings().llm.temperature, ge=0.0, le=2.0, description="Sampling temperature settings determining output determinism.")
    max_tokens: int = Field(default_factory=lambda: get_settings().llm.max_output_tokens, ge=1, description="Absolute limits for allocation window context sizes.")
    timeout_seconds: int = Field(default_factory=lambda: get_settings().llm.request_timeout_seconds, ge=1, description="Per-request HTTP timeout against the LLM endpoint.")
    max_retries: int = Field(default_factory=lambda: get_settings().llm.max_retries, ge=0, description="Retry attempts on transient LLM transport failures.")

    @field_validator("api_key", mode="before")
    @classmethod
    def resolve_api_key(cls, value: Optional[str]) -> Optional[str]:
        """Resolves missing keys from system environment variables where applicable."""
        if not value:
            # For Ollama, the api_key can be any dummy string (it is not checked by the local server)
            return os.getenv("OLLAMA_API_KEY", "ollama-local-bypass-key")
        return value


class GenerationResult(BaseModel):
    """A completion plus the provider's token accounting for that call."""

    text: str = Field(default="", description="The raw text content generated by the model.")
    usage: Dict[str, int] = Field(
        default_factory=dict,
        description="Token counts reported by the provider: prompt_tokens, completion_tokens, total_tokens.",
    )


class LLMClient:
    """
    Encapsulates core connectivity and generation pathways for upstream text models.
    """

    def __init__(self, config: Optional[LLMClientConfig] = None) -> None:
        """
        Initializes the client using explicit settings or system defaults.
        """
        self.config = config or LLMClientConfig()
        
        # Configure connection layers. Passes the active provider's URL to overwrite the
        # SDK's default OpenAI pathway, and bounds each call so an unreachable or wedged
        # endpoint surfaces as an error instead of hanging the request thread.
        self.client = OpenAI(
            api_key=self.config.api_key,
            base_url=self.config.base_url,
            timeout=self.config.timeout_seconds,
            max_retries=self.config.max_retries
        )
        logger.info(
            f"LLM Client successfully initialized. Target Local Model: '{self.config.model_name}' | "
            f"Base Endpoint: '{self.config.base_url}'"
        )

    def generate_with_usage(self, system_prompt: str, user_prompt: str, response_format: Optional[Dict[str, Any]] = None) -> GenerationResult:
        """
        Executes a standard block-level completion request.

        Args:
            system_prompt: System-level framing context or guardrails.
            user_prompt: The core dynamic context string or query statement.
            response_format: Optional dictionary rule to toggle JSON Mode (e.g., {"type": "json_object"}).

        Returns:
            A GenerationResult carrying the generated text and the provider's token usage
            (empty when the endpoint reports none).
        """
        logger.debug(f"Dispatching atomic text generation request to model: {self.config.model_name}")
        
        try:
            kwargs = {
                "model": self.config.model_name,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "temperature": self.config.temperature,
                "max_tokens": self.config.max_tokens,
            }
            if response_format:
                kwargs["response_format"] = response_format

            response = self.client.chat.completions.create(**kwargs)

            usage = {}
            if response.usage is not None:
                usage = {
                    "prompt_tokens": response.usage.prompt_tokens or 0,
                    "completion_tokens": response.usage.completion_tokens or 0,
                    "total_tokens": response.usage.total_tokens or 0,
                }

            return GenerationResult(
                text=response.choices[0].message.content or "",
                usage=usage,
            )

        except APIError as api_err:
            logger.error(f"Downstream LLM API exception intercepted: {str(api_err)}")
            raise RuntimeError(f"LLM service provider failed to complete the request: {str(api_err)}")
        except Exception as e:
            logger.exception("Unexpected system crash inside active client generation path.")
            raise e

    def generate(self, system_prompt: str, user_prompt: str, response_format: Optional[Dict[str, Any]] = None) -> str:
        """
        Executes a completion request and returns only the generated text.

        Convenience wrapper over :meth:`generate_with_usage` for the many call sites that
        do not care about token accounting.

        Args:
            system_prompt: System-level framing context or guardrails.
            user_prompt: The core dynamic context string or query statement.
            response_format: Optional dictionary rule to toggle JSON Mode (e.g., {"type": "json_object"}).

        Returns:
            The raw text content generated by the model.
        """
        return self.generate_with_usage(system_prompt, user_prompt, response_format).text

    def generate_stream(self, system_prompt: str, user_prompt: str) -> Generator[str, None, None]:
        """
        Executes a streaming text request, yielding tokens instantly as they generate.

        Args:
            system_prompt: System-level baseline constraints.
            user_prompt: User question or conversational turn input text.

        Yields:
            Individual token string increments for real-time frontend printing.
        """
        logger.debug(f"Dispatching real-time token stream sequence from model: {self.config.model_name}")
        
        try:
            stream = self.client.chat.completions.create(
                model=self.config.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=self.config.temperature,
                max_tokens=self.config.max_tokens,
                stream=True
            )
            
            for chunk in stream:
                if chunk.choices and chunk.choices[0].delta.content:
                    yield chunk.choices[0].delta.content

        except APIError as api_err:
            logger.error(f"Downstream LLM API exception intercepted during active stream loop: {str(api_err)}")
            raise RuntimeError(f"LLM streaming pipeline failed midway: {str(api_err)}")