"""
Enterprise-Grade Response Parser and JSON Auto-Healing Engine for the KMRL LLM Layer.

Provides robust, fault-tolerant parsing, markdown stripping, bracket-tracking 
extraction, and JSON validation repair mechanics for production LLM outputs.
"""

import json
import logging
import re
import time
from typing import Any, Dict, Type, TypeVar, Optional, Tuple

from pydantic import BaseModel, ValidationError

logger = logging.getLogger("document_intelligence.llm.response_parser_pro")

# Generic type variable bounded to Pydantic BaseModels for strict compiler type safety
T = TypeVar("T", bound=BaseModel)


class LLMResponseParser:
    """
    Advanced, resilient response parser designed to handle and repair 
    structural inconsistencies in LLM-generated payloads.
    """

    def __init__(self) -> None:
        """
        Initializes pre-compiled structural regex patterns for quick execution sweeps.
        """
        # Captures standard markdown code block configurations
        self.markdown_block_pattern = re.compile(r"```(?:json)?\s*(.*?)\s*```", re.DOTALL | re.IGNORECASE)
        
        # Regex patterns for fast defensive data cleaning/healing
        self.trailing_comma_pattern = re.compile(r",\s*([\]}])")  # Fixes: {"a": 1,} -> {"a": 1}
        self.control_chars_pattern = re.compile(r"[\x00-\x1F\x7F]")  # Targets unescaped hidden controls

    def _apply_heuristic_repairs(self, corrupted_text: str) -> str:
        """
        Applies programmatic transformations to repair minor syntax deviations 
        commonly generated by high-temperature or quantized models.
        """
        # Step 1: Strip accidental leading/trailing whitespace blocks
        repaired = corrupted_text.strip()
        
        # Step 2: Fix trailing commas inside arrays or object dictionaries
        repaired = self.trailing_comma_pattern.sub(r"\1", repaired)
        
        # Step 3: Strip out critical control characters that violate standard RFC 8259 JSON specifications
        repaired = self.control_chars_pattern.sub("", repaired)
        
        return repaired

    def _extract_outermost_json_block(self, raw_text: str) -> Tuple[str, bool]:
        """
        Uses explicit bracket balancing to isolate valid JSON maps if the LLM 
        mixed structural codes alongside natural language explanations.
        """
        start_idx = raw_text.find('{')
        if start_idx == -1:
            return raw_text, False
            
        bracket_count = 0
        in_string = False
        escape_char = False
        
        for idx in range(start_idx, len(raw_text)):
            char = raw_text[idx]
            
            # Handle string literal tracking to ignore inner braces inside string values
            if char == '"' and not escape_char:
                in_string = not in_string
            elif char == '\\' and not escape_char:
                escape_char = True
                continue
                
            if escape_char:
                escape_char = False
                
            if not in_string:
                if char == '{':
                    bracket_count += 1
                elif char == '}':
                    bracket_count -= 1
                    if bracket_count == 0:
                        # Successfully closed the target JSON frame
                        return raw_text[start_idx:idx + 1], True
                        
        return raw_text, False

    def extract_json_dict(self, raw_response: str) -> Dict[str, Any]:
        """
        Extracts, sanitizes, heals, and tokenizes a standard python dictionary framework 
        from raw generated strings.

        Args:
            raw_response: Unfiltered execution response buffer from the LLM endpoint.

        Returns:
            A native Python dictionary map containing structured attributes.
        """
        if not raw_response or not raw_response.strip():
            logger.error("Interrupted operational call: target response payload string is null or empty.")
            raise ValueError("Execution engine received an empty context window string.")

        cleaned_text = raw_response.strip()

        # Phase 1: Try standard markdown fence extraction rules
        markdown_matches = self.markdown_block_pattern.findall(cleaned_text)
        if markdown_matches:
            # Use the innermost matching sequence array element
            cleaned_text = markdown_matches[0].strip()
        else:
            # Phase 2: Implement defensive bracket-tracking isolation if conversational noise wraps the code
            cleaned_text, isolated = self._extract_outermost_json_block(cleaned_text)

        # Phase 3: Execute initial standard parsing attempt
        try:
            return json.loads(cleaned_text)
        except json.JSONDecodeError:
            logger.warning("Standard JSON validation failed. Executing heuristic structural repairs...")

        # Phase 4: Execute advanced syntax structural auto-healing passes
        healed_text = self._apply_heuristic_repairs(cleaned_text)
        try:
            parsed_data = json.loads(healed_text)
            if not isinstance(parsed_data, dict):
                raise ValueError("Payload successfully parsed but evaluated into a non-dictionary sequence data frame.")
            logger.info("JSON auto-healing loop successfully repaired corrupted string metrics.")
            return parsed_data
        except json.JSONDecodeError as decode_err:
            logger.critical(f"Irreparable structural formatting break encountered. Error offset tracking: {str(decode_err)}")
            logger.debug(f"Failed string context dump:\n{cleaned_text}")
            raise ValueError(f"LLM output could not be parsed into valid structural JSON: {str(decode_err)}")

    def parse_to_pydantic(self, raw_response: str, model_class: Type[T]) -> T:
        """
        Parses an LLM string directly into a strongly typed Pydantic validation model.
        Captures operational metrics and records schema performance insights.

        Args:
            raw_response: The raw string output returned by the LLM client.
            model_class: The target Pydantic class to validate the extracted data against.

        Returns:
            An instantiated, validated object of the requested Pydantic model class.
        """
        start_time = time.perf_counter()
        logger.debug(f"Initiating pro compilation cycle mapping onto schema profile: {model_class.__name__}")

        # Step 1: Resilient dictionary isolation pass
        extracted_dict = self.extract_json_dict(raw_response)

        # Step 2: Validate the dictionary map against the Pydantic constraints
        try:
            validated_instance = model_class.model_validate(extracted_dict)
            latency = (time.perf_counter() - start_time) * 1000
            logger.debug(f"Schema transformation verified successfully in {latency:.2f}ms.")
            return validated_instance
            
        except ValidationError as val_err:
            latency = (time.perf_counter() - start_time) * 1000
            logger.error(
                f"Validation breach mapping output schema onto structural class: {model_class.__name__}. "
                f"Total compilation duration: {latency:.2f}ms."
            )
            # Log exact field paths violating schemas to simplify telemetry parsing updates
            for error in val_err.errors():
                loc_path = " -> ".join(str(p) for p in error.get("loc", []))
                logger.error(f"[@ Field: {loc_path or 'Root'}] Message Context: {error.get('msg')} ({error.get('type')})")
                
            raise ValueError(f"Schema normalization metrics failed target layout validations: {str(val_err)}")